### ISSUE TITLE
Doesn't work with `evil-undo`

### ISSUE THREAD

**Issue by hkjels** [casouri/undo-hl#3]
I see that `evil-undo` is essentially aliased to 'undo, so I'm not sure why calling 'undo directly makes a difference. I could dig deeper, but it's not at the top of my list right now. I thought maybe you would want to know about it though

**Comment by casouri** [comment]
Simple, just add `evil-undo` to `undo-hl-undo-commands`. I can do that. What other undo commands does evil use?

**Comment by hkjels** [comment]
That did the trick! `evil` has `evil-undo` & `evil-redo`.
