### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by LaurenceWarne** [casouri/undo-hl#4]
When I see `Download the package` in `Usage` I assumed it would be on melpa or something, but it appears (?) the package needs to be downloaded manually.

Would you consider adding the package to melpa or another common package archive?

But anyway the package seems really useful so far so thanks!

**Comment by casouri** [comment]
This is a relatively new package so it is not available on MELPA or ELPA. I'll probably put it on MELPA in the future, since many people expressed interest of using it!

**Comment by LaurenceWarne** [comment]
:+1: (maybe add @jlagneau 's snippet to the README?)

Closing, but feel free to re open to keep it as a reminder :slightly_smiling_face:
